import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/src/components/dashboard/navbar";
import Sidenav from "@/src/components/dashboard/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen w-full">
      <Sidenav />
      <div className="flex flex-col lg:ml-64">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
